sonar.projectKey=devops-url-shortener
sonar.projectName=DevOps URL Shortener
sonar.sources=backend,frontend
sonar.tests=tests
sonar.python.version=3.13
sonar.exclusions=**/node_modules/**,**/dist/**,.scannerwork/**